version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: rollup-plugin-chrome-extension
    versions:
    - ">= 3.a, < 4"
  - dependency-name: "@rollup/plugin-typescript"
    versions:
    - 8.1.0
    - 8.1.1
    - 8.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
  - dependency-name: rollup-plugin-iife
    versions:
    - 0.4.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.0.1
    - 11.1.1
