name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load cache
        uses: actions/cache@v2
        with:
         path: node_modules
         key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: "Save build"
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist/learn-the-shortcuts.zip
