name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: "Save build"
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist/learn-the-shortcuts.zip
